-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- *** RESET DATABASE (CAUTION: THIS DELETES ALL DATA) ***
drop table if exists public.favorites cascade;
drop table if exists public.comics cascade;
drop table if exists public.profiles cascade;
drop function if exists public.handle_new_user cascade;


-- 1. PROFILES TABLE: Minimal reference to auth.users
-- We only store ID and Email as requested.
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  nombre varchar(100),
  email text,
  updated_at timestamp with time zone
);

-- 2. COMICS TABLE: List of available comics
create table public.comics (
  id bigint generated by default as identity primary key,
  title text not null,
  issue_number text,
  description text,
  cover_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. FAVORITES TABLE: Link users to their favorite comics
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  comic_id bigint references public.comics(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, comic_id) -- Prevent duplicate favorites
);

-- 4. ROW LEVEL SECURITY (RLS)
alter table public.profiles enable row level security;
alter table public.comics enable row level security;
alter table public.favorites enable row level security;

-- Policies for PROFILES
create policy "Users can view own profile."
  on profiles for select
  using ( auth.uid() = id );

-- Policies for COMICS (Read-only for users, Admin manages content)
create policy "Comics are viewable by everyone."
  on comics for select
  using ( true );

-- Policies for FAVORITES
create policy "Users can view own favorites."
  on favorites for select
  using ( auth.uid() = user_id );

create policy "Users can add favorites."
  on favorites for insert
  with check ( auth.uid() = user_id );

create policy "Users can remove own favorites."
  on favorites for delete
  using ( auth.uid() = user_id );

-- 5. AUTOMATIC PROFILE CREATION TRIGGER
-- Automatically creates a profile entry when a new user signs up (Email or Google)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid errors on multiple runs
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. SEED DATA
insert into public.comics (title, issue_number, description, cover_url)
select 'The Amazing Spider-Man', '#1', 'Spider-Man meets the Fantastic Four!', 'https://i.annihil.us/u/prod/marvel/i/mg/6/c0/5909d2e7dcb30/clean.jpg'
where not exists (select 1 from public.comics limit 1);

insert into public.comics (title, issue_number, description, cover_url)
select 'Secret Wars', '#8', 'Origin of the Black Suit (Symbiote)', 'https://i.annihil.us/u/prod/marvel/i/mg/f/00/5be4630e52706/clean.jpg'
where not exists (select 1 from public.comics where title = 'Secret Wars');
